name: pnPm

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnPm
        uses: pnpm/action-setup@v4

      - name: Setup NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        working-directory: ./web
        run: pnpm install

      - name: Test
        working-directory: ./web
        run: pnpm test

      - name: Build
        working-directory: ./web
        run: pnpm build
